"""
Entry point to the project (in production).
"""

from __future__ import annotations

from pathlib import Path
import os
# import sys
import shutil
import json
import logging
import logging.config

project_root = Path(__file__).resolve().parent

temp_path = project_root / "Temp"
uploads_path = project_root / "Uploads"

temp_path.mkdir(exist_ok=True)
uploads_path.mkdir(exist_ok=True)

os.environ["GRADIO_TEMP_DIR"] = str(uploads_path)

import gradio as gr

from make_sense.parser import MarkerSettings, pdf_2_md
from make_sense.model import generate_explanation
from make_sense.pandoc import save_model_response

IDLE_STATE = ("Explain Paper", gr.update(visible=True), gr.update(visible=False), None)

def setup_logging(config_path: Path) -> None:
    """
    Configure application logging.
    """

    try:
        with config_path.open("r", encoding="utf-8") as f:
            config = json.load(f)

        logging.config.dictConfig(config)

    except FileNotFoundError:
        logging.basicConfig(level=logging.INFO)
        logging.error("Logging configuration file %s not found. Using basic logging.", str(config_path))


logger = logging.getLogger("make_sense")

def clear_temp_folder() -> None:
    """
    Remove files generated by the previous processing run.

    Gradio uploads are stored in Uploads/, so this only clears our application's Temp/ directory.
    """

    if not temp_path.exists():
        temp_path.mkdir(parents=True, exist_ok=True)
        return

    for item in temp_path.iterdir():
        try:

            if item.is_file() or item.is_symlink():
                item.unlink()

            elif item.is_dir():
                shutil.rmtree(item)

        except Exception:
            logger.exception("Failed to remove temporary item: %s",item)
            raise


def pipeline(pdf_file: str | None):
    """
    Process an uploaded PDF.
    """

    if not pdf_file:
        yield IDLE_STATE
        raise gr.Error("Please upload a PDF first.")

    uploaded_path = Path(pdf_file).resolve()

    logger.info("Gradio uploaded file: %s",uploaded_path)

    if not uploaded_path.is_file():
        logger.error("Gradio supplied a file that does not exist: %s",uploaded_path)
        yield IDLE_STATE
        raise gr.Error(f"Uploaded PDF could not be found:\n{str(uploaded_path)}")

    if uploaded_path.suffix.lower() != ".pdf":
        yield IDLE_STATE
        raise gr.Error("Please upload a PDF file.")

    yield ("Preparing PDF...", gr.update(visible=True), gr.update(visible=False), None)

    try:
        clear_temp_folder()

    except Exception as e:
        logger.exception("Failed to clear Temp directory.")
        yield IDLE_STATE
        raise gr.Error(f"Could not prepare temporary directory: {e}")

    working_path = temp_path / uploaded_path.name

    logger.info("Working PDF path: %s",str(working_path))

    yield ("Copying PDF...", gr.update(visible=True), gr.update(visible=False), None)

    try:

        shutil.copy2(uploaded_path, working_path)

    except Exception as e:
        logger.exception("Failed to copy uploaded PDF from %s to %s", str(uploaded_path), str(working_path))
        yield IDLE_STATE
        raise gr.Error(f"Could not copy uploaded PDF: {e}")

    if not working_path.is_file():
        logger.error("PDF copy operation completed but file does not exist: %s", str(working_path))
        yield IDLE_STATE
        raise gr.Error("Could not prepare the uploaded PDF for processing.")

    logger.info("Copied PDF successfully: %s -> %s",str(uploaded_path), str(working_path))

    yield ("Converting PDF to Markdown...", gr.update(visible=True), gr.update(visible=False), None)

    try:

        logger.info("Running pdf_2_md(%s)",str(working_path))

        md_path = pdf_2_md(settings.model_dump(), working_path)

        logger.info("Markdown created successfully: %s",str(md_path))

    except Exception as e:

        logger.exception("PDF to Markdown conversion failed.")
        yield IDLE_STATE
        raise gr.Error(f"PDF conversion failed: {e}")

    yield("Generating explanation...", gr.update(visible=True), gr.update(visible=False), None)

    try:

        logger.info("Running generate_explanation(%s)", str(md_path))

        response_path = generate_explanation(md_path, api_key=os.environ.get("OPENROUTER_API_KEY","",))

        logger.info("Model response created: %s", str(response_path))

    except Exception as e:

        logger.exception("Explanation generation failed.")
        yield IDLE_STATE
        raise gr.Error(f"Explanation generation failed: {e}")

    yield ("Creating final PDF...", gr.update(visible=True), gr.update(visible=False), None)

    try:

        logger.info("Running save_model_response(..)")

        pdf_path = save_model_response(response_path, working_path.stem)

        pdf_path = Path(pdf_path).resolve()

        if not pdf_path.is_file():
            raise FileNotFoundError(f"Final PDF was not created: {str(pdf_path)}")

        logger.info("Final PDF created successfully: %s", str(pdf_path))

    except Exception as e:

        logger.exception("Final PDF creation failed.")
        yield IDLE_STATE
        raise gr.Error(f"Could not create final PDF: {e}")

    logger.info("Pipeline completed successfully.")

    yield ("Explained PDF is ready!", gr.update(visible=False), gr.update(visible=True), str(pdf_path))


if __name__ == "__main__":

    setup_logging(project_root / "logging_config.json")

    logger.info("Starting Make Sense...")

    logger.info("Project root: %s", str(project_root))

    logger.info("Temp directory: %s", str(temp_path))

    logger.info("Gradio upload directory: %s", str(uploads_path))

    marker_config_path = project_root / "marker_config.json"

    if not marker_config_path.exists():

        logger.critical(
            "Unable to find marker_config.json: %s",
            marker_config_path,
        )

        gr.Error("Unable to find marker_config.json.")
        # sys.exit("Unable to find marker_config.json.")

    config: dict = json.loads(marker_config_path.read_text(encoding="utf-8"))

    settings = MarkerSettings(**config)

    with gr.Blocks(title="Make Sense", delete_cache=(86400, 86400)) as demo:

        gr.Markdown(
            """
            # Make Sense

            Upload a research paper and get an explained PDF.
            """
        )

        pdf_input = gr.File(
            label="Upload a paper PDF",
            file_types=[".pdf"],
            type="filepath",
        )

        submit_button = gr.Button(
            "Explain Paper",
            variant="primary",
        )

        download_button = gr.DownloadButton(
            label="Download Explained PDF",
            visible=False,
        )

        submit_button.click(
            fn=pipeline,
            inputs=pdf_input,
            outputs=[
                submit_button,
                submit_button,
                download_button,
                download_button,
            ],
            show_progress="hidden"
        )


    demo.queue().launch()